# Generated by Django 3.2 on 2022-03-21 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raitng', '0002_alter_raiting_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='star',
            field=models.CharField(choices=[('0', ''), ('1', 'Ненависть'), ('2', 'Неприязнь'), ('3', 'Нейтрально'), ('4', 'Обожание'), ('5', 'Любовь')], default=0, max_length=1),
        ),
    ]
