# Generated by Django 3.2 on 2022-03-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raitng', '0004_raiting_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raiting',
            options={'verbose_name': 'Оценка', 'verbose_name_plural': 'Оценки'},
        ),
    ]
