# Generated by Django 3.2 on 2022-03-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raitng', '0006_raiting_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raiting',
            name='item',
        ),
    ]
