# Generated by Django 3.2 on 2022-03-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raitng', '0009_raiting_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='raiting',
            constraint=models.UniqueConstraint(fields=('user', 'item'), name='unique_raiting'),
        ),
    ]
