# Generated by Django 3.2 on 2022-03-25 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0005_auto_20220325_0855'),
        ('raitng', '0010_raiting_unique_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='item',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.item'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
