# Generated by Django 3.2 on 2022-04-26 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20220426_1816'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raitng', '0012_auto_20220326_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raiting',
            name='item',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to='catalog.item', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='star',
            field=models.CharField(choices=[('0', ''), ('1', 'Ненависть'), ('2', 'Неприязнь'), ('3', 'Нейтрально'), ('4', 'Обожание'), ('5', 'Любовь')], default='0', max_length=1, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='raiting',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='raitings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
