# Generated by Django 3.2 on 2022-03-25 08:55

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220323_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[catalog.validators.validate_eng], verbose_name='Жетон'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(null=True, to='catalog.Tag', verbose_name='Тэг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='text',
            field=models.TextField(null=True, validators=[catalog.validators.validate_brilliant], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True, validators=[catalog.validators.validate_eng], verbose_name='Жетон'),
        ),
    ]
