# Generated by Django 3.2 on 2022-04-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='item',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='catalog.category', verbose_name='Категория'),
        ),
    ]
